#! /bin/bash
if [ builder/builder/Tasks.java -nt builder/builder/Tasks.class ] || [ builder/builder/BuildUtils.java -nt builder/builder/BuildUtils.class ]; then
	cd builder
	javac -cp "libs/*" builder/*.java
	cd ..
fi
java -cp "builder:builder/libs/*" builder.BuildUtils "$@"
