#!/usr/bin/env bash

# shell script to tell if tomcat is running or not

if [ 0 = `ps lax |grep -v grep |grep catalina.startup.Bootstrap |wc -l` ]; then
	echo tomcat is not running
else
	echo tomcat is running
fi


