#!/usr/bin/env bash

# I've found that I often use multiple front-ends with a single back-end.
# So, this single back-end has no front-end code.  This script
# removes the front-end portion of the system to give me a convenient 
# starting point for a back-end-only project.

if [ $# -ne 1 ] || [ 'remove' != $1 ]; then
	echo
	echo 'This script removes the back-end portion of Kiss'
	echo
	echo Usage: $0 remove
	echo
	exit
fi

rm -rf src/main/frontend
rm -rf .git* remove-backend* make-frontend SimpleWebServer.jar upgrade-kiss* *.md
rm -rf expand LICENSE.txt list-both serv* shrink make-frontend*

