package org.kissweb.oauth.as;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Immutable representation of an OAuth client registered with the
 * authorization server.  Clients are created either statically (by code
 * calling {@link ClientStore#register}) or dynamically via the
 * {@code /oauth/register} endpoint (RFC 7591).
 * <br><br>
 * Two client kinds:
 * <ul>
 *   <li>\emph{Public client} --- no client secret, typically an SPA,
 *       native app, or MCP desktop client.  Authenticates using PKCE
 *       alone, never sends a {@code client_secret} on the token
 *       endpoint.</li>
 *   <li>\emph{Confidential client} --- has a {@code client_secret},
 *       typically a server-side application.  Sends the secret with
 *       every token request (via HTTP Basic auth or
 *       {@code client_secret_post}).</li>
 * </ul>
 */
public final class RegisteredClient {

    private final String       clientId;
    /** SHA-256 hex of the secret, or null for public clients. */
    private final String       clientSecretHash;
    private final String       clientName;
    private final List<String> redirectUris;
    private final Set<String>  allowedScopes;
    private final Set<String>  allowedGrantTypes;
    private final boolean      publicClient;
    private final long         createdAtEpochSeconds;

    /**
     * Construct an immutable client record.
     *
     * @param clientId              the client identifier (generated by DCR or supplied by static registration)
     * @param clientSecretHash      SHA-256 hex of the client secret, or null for a public client
     * @param clientName            human-readable client name (shown on the consent page)
     * @param redirectUris          allowed redirect URIs --- the {@code redirect_uri} parameter on /authorize must match one of these exactly
     * @param allowedScopes         scopes the client may request; tokens issued to this client cannot exceed this set
     * @param allowedGrantTypes     grant types this client may use (typically {@code authorization_code} and {@code refresh_token})
     * @param createdAtEpochSeconds when the client was created (Unix epoch seconds)
     */
    public RegisteredClient(String clientId,
                            String clientSecretHash,
                            String clientName,
                            List<String> redirectUris,
                            Set<String> allowedScopes,
                            Set<String> allowedGrantTypes,
                            long createdAtEpochSeconds) {
        this.clientId              = clientId;
        this.clientSecretHash      = clientSecretHash;
        this.clientName            = clientName;
        this.redirectUris          = Collections.unmodifiableList(redirectUris);
        this.allowedScopes         = Collections.unmodifiableSet(new LinkedHashSet<>(allowedScopes));
        this.allowedGrantTypes     = Collections.unmodifiableSet(new LinkedHashSet<>(allowedGrantTypes));
        this.publicClient          = clientSecretHash == null;
        this.createdAtEpochSeconds = createdAtEpochSeconds;
    }

    /**
     * Get the client identifier.
     * @return the client identifier
     */
    public String getClientId() { return clientId; }

    /**
     * Get the SHA-256 hex of the client secret.
     * @return SHA-256 hex of the client secret, or null for a public client
     */
    public String getClientSecretHash() { return clientSecretHash; }

    /**
     * Get the human-readable client name (shown on consent).
     * @return human-readable client name (shown on consent)
     */
    public String getClientName() { return clientName; }

    /**
     * Get the allowed redirect URIs (exact-match list).
     * @return the allowed redirect URIs (exact-match list)
     */
    public List<String> getRedirectUris() { return redirectUris; }

    /**
     * Get the scopes this client is permitted to request.
     * @return scopes this client is permitted to request
     */
    public Set<String> getAllowedScopes() { return allowedScopes; }

    /**
     * Get the grant types this client is permitted to use.
     * @return grant types this client is permitted to use
     */
    public Set<String> getAllowedGrantTypes() { return allowedGrantTypes; }

    /**
     * Check whether this is a public client (no client_secret).
     * @return true if this is a public client (no client_secret)
     */
    public boolean isPublicClient() { return publicClient; }

    /**
     * Get when the client was registered (Unix epoch seconds).
     * @return when the client was registered (Unix epoch seconds)
     */
    public long getCreatedAtEpochSeconds() { return createdAtEpochSeconds; }

    /**
     * Test whether the given URI is one of this client's allowed
     * redirect URIs (exact-match per OAuth 2.1).
     *
     * @param uri the candidate redirect URI
     * @return true if exactly one of the registered URIs equals this URI
     */
    public boolean hasRedirectUri(String uri) {
        return uri != null && redirectUris.contains(uri);
    }
}
